plugins {
    alias(libs.plugins.android.application)      // Standard Android application plugin
    alias(libs.plugins.google.services)          //  Enables Firebase services (auth, firestore, etc.)
}

android {
    namespace = "bd.edu.seu.cookify"            // App's package namespace
    compileSdk = 36                              // Compile against SDK version 36

    defaultConfig {
        applicationId = "bd.edu.seu.cookify"    // Unique identifier of your app
        minSdk = 24                              // Minimum Android version supported
        targetSdk = 36                           // Version app is optimized for
        versionCode = 1                          // Internal version number for updates
        versionName = "1.0"                      // User-visible app version

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner" // Runner for instrumented tests
    }

    buildTypes {
        release {
            isMinifyEnabled = false              // Disable code shrinking for now
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"), // Default Proguard rules
                "proguard-rules.pro"                                   // Custom Proguard rules
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17  // Java version used to compile source code
        targetCompatibility = JavaVersion.VERSION_17  // Java version for generated bytecode
    }
}

dependencies {
    //  Firebase BOM ensures all Firebase libraries use compatible versions automatically
    implementation(platform("com.google.firebase:firebase-bom:32.7.0"))

    // Load images from URLs into ImageViews
    implementation("com.squareup.picasso:picasso:2.8")

    //  Firebase Authentication for email/password login
    implementation(libs.firebase.auth)

    //  Google Sign-In SDK for OAuth login
    implementation("com.google.android.gms:play-services-auth:21.0.0")

    // AndroidX and Material libraries for UI components
    implementation(libs.appcompat)
    implementation(libs.material)

    // Cloud Firestore database
    implementation(libs.firebase.firestore)

    // RecyclerView for listing recipes and CardView for item cards
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("androidx.cardview:cardview:1.0.0")


    implementation ("com.github.bumptech.glide:glide:4.15.1")
    annotationProcessor ("com.github.bumptech.glide:compiler:4.15.1")


    //  Testing libraries
    testImplementation("junit:junit:4.13.2")                     // Unit tests
    androidTestImplementation("androidx.test.ext:junit:1.1.5")  // AndroidX JUnit tests
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1") // UI tests

}
